name: Build and Upload Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate timestamp and random string tag
        id: tag
        run: |
          # 生成随机字符串
          RANDOM_STRING=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1)
          # 生成基于年月日的标签
          TIMESTAMP_TAG=$(date +'%Y%m%d')-$RANDOM_STRING
          echo "TAG=$TIMESTAMP_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            shed219/exloli-next:latest
            shed219/exloli-next:${{ steps.tag.outputs.TAG }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Check build output
        run: |
          echo "Image digest: ${{ steps.build-and-push.outputs.digest }}"
          echo "Image size: ${{ steps.build-and-push.outputs.size }}"
          echo "Image ID: ${{ steps.build-and-push.outputs.image-id }}"
