name: Build and Upload Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate timestamp and random string tag
        id: tag
        run: |
          TIMESTAMP_TAG=$(date +'%Y%m%d')
          RANDOM_STRING=$(openssl rand -hex 3)
          FINAL_TAG="${TIMESTAMP_TAG}-${RANDOM_STRING}"
          echo "TAG=${FINAL_TAG}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            shed219/exloli-next:latest
            shed219/exloli-next:${{ steps.tag.outputs.TAG }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      # 其他步骤...
